server:
  port: 8000
  servlet:
    context-path: /api/core/*

spring:
  application:
    name: core-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/core
    username: ${DB_USER:core}
    password: ${DB_PASS:root}
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
  flyway:
    out-of-order: false

application:
  security:
    signature: ${SIGNATURE:key}
    lifetime: 7d
    github:
      secret: ${GITHUB_SECRET:d3e30a0d4e1e21f748867b98a81b9408e931f32c}
      client-id: ${CLIENT_ID:a8c13358da0525d4da5b}
